### PR TITLE
Doxygen

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Pull Request Summary
 

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):    
* Please indicate the expected changes in the regression test output ([Note the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA  Whoops, I grazed over this PR a bit ago. I thought it was one created while we were doing some practice.. sorry it wasn't addressed.  

Currently this branch has been inactive, and the marked docs from myself and C. Bunney have already been commited in a different PR to NOAA-EMC.  I've pulled in all your changes into my currently active doxygen branch, [doxy3jm](https://github.com/MatthewMasarik-NOAA/WW3/tree/doxy3jm).  

I'd like to close this branch and proceed with doxy3jm.  Does that work for you?

**Comment by JessicaMeixner-NOAA** [comment]
Should I make the PR to another branch or can you just pull in my change from my branch into whatever branch you'd like?

**Comment by MatthewMasarik-NOAA** [comment]
I've already merged in your changes to the branch doxy3jm, so everything is set and no action needed.

**Comment by JessicaMeixner-NOAA** [comment]
Okay I'll closes this PR then.

**Comment by MatthewMasarik-NOAA** [comment]
Perfect, thanks!

**Pull request closed without merging**
